Feat: error TS6133: 'variable' is declared but its value is never read. Go to tsconfig.app.json and turn the false to true for noUnusedLocals and Parameters